#!/usr/bin/env bash

set -eo pipefail

AZURE_CLI_VERSION="2.22.1-1~buster"
TERRAFORM_VERSION="0.15.1"
DATABRICKS_CLI_VERSION="0.14.3"

./dev-build.sh ${AZURE_CLI_VERSION} ${TERRAFORM_VERSION} ${DATABRICKS_CLI_VERSION}