#!/usr/bin/env bash

set -eo pipefail

AZURE_CLI_VERSION="2.19.1"
TERRAFORM_VERSION="0.14.6"
DATABRICKS_CLI_VERSION="0.14.1"

./dev-build.sh ${AZURE_CLI_VERSION} ${TERRAFORM_VERSION} ${DATABRICKS_CLI_VERSION}