#!/bin/bash

set -e

RELEASE_VERSION=${RELEASE_VERSION:-"1.0"}
AZURE_CLI_VERSION=${AZURE_CLI_VERSION:-"2.19.1"}
TERRAFORM_VERSION=${TERRAFORM_VERSION:-"0.14.6"}
DATABRICKS_CLI_VERSION=${DATABRICKS_CLI_VERSION:-"0.14.1"}

TAG="release-${RELEASE_VERSION}_terraform-${AZURE_CLI_VERSION}_azcli-${TERRAFORM_VERSION}_databricks-${DATABRICKS_CLI_VERSION}"

# Parse image name for repo name
tagStart=$(expr index "$IMAGE_NAME" :)
repoName=${IMAGE_NAME:0:tagStart-1}

# Tag and push image for each additional tag
for tag in {${TAG},latest}; do
    docker tag $IMAGE_NAME ${repoName}:${tag}
    docker push ${repoName}:${tag}
done