#!/bin/bash

set -e

RELEASE_VERSION=${RELEASE_VERSION:-"1.1"}
AZURE_CLI_VERSION=${AZURE_CLI_VERSION:-"2.22.1"}
TERRAFORM_VERSION=${TERRAFORM_VERSION:-"0.15.1"}
DATABRICKS_CLI_VERSION=${DATABRICKS_CLI_VERSION:-"0.14.3"}

TAG="release-${RELEASE_VERSION}_terraform-${TERRAFORM_VERSION}_azcli-${AZURE_CLI_VERSION}_databricks-${DATABRICKS_CLI_VERSION}"

# Parse image name for repo name
tagStart=$(expr index "$IMAGE_NAME" :)
repoName=${IMAGE_NAME:0:tagStart-1}

# Tag and push image for each additional tag
for tag in {${TAG},latest}; do
    docker tag $IMAGE_NAME ${repoName}:${tag}
    docker push ${repoName}:${tag}
done